name: euchre
description: "Euchre Card Game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.4.0
  card_game: ^2.0.0
  collection:
  confetti: ^0.8.0
  equatable: ^2.0.7
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.0.17
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  vector_graphics: ^1.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/backs/
    - assets/faces/
    - assets/sounds/
